# Generated by Django 3.0.5 on 2020-05-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'permissions': (('can_review_recipe', 'Can review Recipe'),)},
        ),
    ]
