# Generated by Django 3.0.4 on 2020-03-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='describtion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='recipes',
            name='preparation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipes',
            name='work_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(to='foodApp.Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
