# Generated by Django 3.0.4 on 2020-03-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0003_auto_20200324_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='describtion',
            new_name='description',
        ),
    ]
